[package]
name = "mongodb-support"
version = "0.1.0"
edition = "2021"

[dependencies]
dc-api-types = { path = "../dc-api-types" }
enum-iterator = "1.4.1"
schemars = "^0.8.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
