[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "^0.12"
mongodb = "2.8"
mongodb-support = { path = "../mongodb-support" }
schemars = "^0.8.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_yaml = "^0.9"
tokio = "1"
